export const START_DATE = new Date('2027-01-01T00:00:00');
export const TOTAL_DAYS = 624;
export const TOTAL_BOOKS = 257;

export const SIDEBAR_DB = {
    books: [
        { title: "KATMAN 0-1: Metodoloji ve Zemin", list: ["Nasıl Okumalı - M. Adler", "Deep Work - Cal Newport", "Make It Stick - Brown", "Hızlı ve Yavaş Düşünme - Kahneman", "Batı Felsefesi Tarihi - B. Russell", "İslam Düşüncesine Giriş - M.M. Şerif", "Batı Düşüncesi Tarihi - R. Tarnas", "Sanatın Öyküsü - E.H. Gombrich", "Sapiens - Y.N. Harari", "Zamanın Kısa Tarihi - S. Hawking", "Akışkan Zeka - R. Cattell", "Atom Alışkanlıklar - J. Clear", "Zihin Haritaları - T. Buzan", "Limitless - J. Kwik", "Mastery - J. Kwik", "Bilinçaltının Gücü - J. Murphy"] },
        { title: "KATMAN 2-3: İman, Kelam ve Usul", list: ["Kur'an-ı Kerim Meali", "Riyâzüssâlihîn", "Buhârî (Seçme Hadisler)", "Siyer-i Nebî", "El-Munkız mine'd-Dalâl - İmam Gazali", "Er-Risâle - İmam Şafii", "Organon - Aristoteles", "Tehâfüt el-Felâsife - Gazali", "Tehâfüt et-Tehâfüt - İbn Rüşd", "Yöntem Üzerine Konuşma - Descartes", "Saf Aklın Eleştirisi - I. Kant", "Etika - Spinoza", "Tahâviyye Akidesi", "Fıkıh Usulü El Kitabı", "Retorik - Aristoteles", "İslam Kelamı - M. Özervarlı"] },
        { title: "KATMAN 4-6: Epistemoloji ve İrade", list: ["Bilimsel Devrimlerin Yapısı - T. Kuhn", "Yanlışlanabilirlik - K. Popper", "Kara Kuğu - N. Taleb", "Antikırılganlık - N. Taleb", "Feynman Fizik Dersleri", "İnsanın Anlam Arayışı - V. Frankl", "Can't Hurt Me - D. Goggins", "On Combat - D. Grossman", "The Flinch - J. Smith", "Resilience - E. Greitens", "Kalbin Tasfiyesi - Hamza Yusuf", "Düşünceler - Epiktetos", "Kendime Düşünceler - M. Aurelius", "Ahlak Mektupları - Seneca", "Böyle Buyurdu Zerdüşt - F. Nietzsche", "İnsan Olma Sanatı - A. Adler", "Keşfedilmemiş Benlik - C.G. Jung"] },
        { title: "KATMAN 7-8: Kitle, Algı ve Müzakere", list: ["İnsan Doğası Üzerine - Schopenhauer", "Kitlelerin Psikolojisi - G. Le Bon", "Propaganda - E. Bernays", "İtaat Deneyleri - S. Milgram", "İkna'nın Psikolojisi - R. Cialdini", "Pitch Anything - O. Klaff", "Asla Farkı Bölüşme - C. Voss", "The Secrets Dialogue & Persuasion - S. Qaiman", "Hatip Üzerine - Cicero (YENİ)", "TED Gibi Konuş - Carmine Gallo (YENİ)", "Amusing Ourselves to Death - N. Postman", "Understanding Media - M. McLuhan", "Algı Yönetimi - M. Tarhan", "Kitle ve İktidar - E. Canetti (Giriş)", "Sessiz Yığınlar - J. Baudrillard", "Toplum Sözleşmesi - J.J. Rousseau"] },
        { title: "KATMAN 9-10: Güç ve Kurucu Otorite", list: ["Savaş Sanatı - Sun Tzu", "Savaş Üzerine - Clausewitz", "Strateji - B. Liddell Hart", "Prens - Machiavelli", "İktidar: 48 Yasa - R. Greene", "Savaşın 33 Stratejisi - R. Greene", "Ekonomi ve Toplum (Karizmatik Otorite) - M. Weber", "The Sovereign Individual - Davidson", "From Third World to First - Lee Kuan Yew", "Ulusların Zenginliği - A. Smith", "Temel Ekonomi - T. Sowell", "Kölelik Yolu - F. Hayek", "Kapitalizm, Sosyalizm ve Demokrasi - J. Schumpeter", "Uluslararası Politika - H. Morgenthau", "Siyasal Kavramı - C. Schmitt"] },
        { title: "KATMAN 11-13: İslam Siyaseti ve Medeniyet", list: ["Kitleler ve İktidar - E. Canetti (Derinleme)", "Mukaddime - İbn Haldun", "Siyasetname - Nizamülmülk", "El-Ahkâmu's-Sultâniyye - Maverdî", "Devlet - Platon", "Büyük Satranç Tahtası - Z. Brzezinski", "Medeniyetlerin Çatışması - S. Huntington", "Tarih Bilinci - A. Toynbee", "Maddi Uygarlık - F. Braudel", "Tüfek, Mikrop ve Çelik - J. Diamond", "Ulusların Düşüşü - D. Acemoğlu", "Tanah (Eski Ahit)", "İncil (Yeni Ahit)", "Bhagavad Gita", "Tao Te Ching - Laozi", "Dhammapada (Buda'nın Yolu)"] },
        { title: "KATMAN 14 & 17: Sentez ve Alegori (Edebiyat)", list: ["1984 - G. Orwell", "Hayvan Çiftliği - G. Orwell", "Veba - A. Camus", "Yabancı - A. Camus", "Dönüşüm - F. Kafka", "Dava - F. Kafka", "Cesur Yeni Dünya - A. Huxley", "Rubailer - Ömer Hayyam", "İlahi Komedya - Dante", "Kur'an'da Allah ve İnsan - T. Izutsu", "İslam'da Dini Düşüncenin İnşası - M. İkbal", "Nehcü'l-Belağa - Hz. Ali", "Hak Dini Kur'an Dili (Özet) - E. Hamdi Yazır", "Tefsir-i Kebir (Seçki) - F. Râzî", "Kahramanın Sonsuz Yolculuğu - J. Campbell"] },
        { title: "HALVET: 3. Göz, Kalp ve Seyr-i Süluk", list: ["Mantıku't-Tayr (Kuşların Dili) - F. Attar", "Makâlât - Şems-i Tebrizi", "İhyâ'u Ulûmi'd-Dîn - İmam Gazali", "Füsûsu'l-Hikem - İbn Arabi", "El-Fütûhât el-Mekkiyye - İbn Arabi", "Mektubat - İmam Rabbani", "Mesnevi (Seçkiler) - Mevlana", "El-Lüma - Ebu Nasr es-Serrac", "Kuşeyri Risalesi", "Kimya-yı Saadet - İmam Gazali"] }
    ],
    supplements: [
        { name: "Longevity Mix: NMN & Spermidine & Shilajit", note: "Sabah 04:30. Bryan Johnson protokolü (Hücresel gençlik, otofaji) ile Himalayaların ATP patlaması tek formülde." },
        { name: "Kadim Sır: Akgünlük (Boswellia) & Çörek Otu", note: "Sabah aç. İbn Arabi ve İslam alimlerinin hafıza ve kalp gözü (Epifiz) için çiğnediği/içtiği formül." },
        { name: "Seremoniyel Matcha & Lion's Mane (1.8g)", note: "Deep Work (06:00) öncesi. Titremesiz odak, BDNF (Sinir büyüme faktörü) ve nörogenez şalteri." },
        { name: "Temel Zırh: D3(4000 IU) + K2(100mcg) + Çinko(15mg)", note: "İlk öğünle alınır. K2 olmadan D3 kalsiyumu kemiğe taşıyamaz. Çinko ise testosteron kalkanıdır." },
        { name: "Mizaç & Bağırsak: Sirkencübin + Probiyotik (30B)", note: "İbn Sina'nın mizaç dengeleyici içeceği ile modern 30 Milyar CFU probiyotiğin ikinci beyni onarımı." },
        { name: "L-Tirozin (500mg)", note: "Ağır antrenman sonrası. Çarpışmada tükenen Dopamin rezervini hızla doldurur." },
        { name: "Detoks & Uyku: NAC (600mg) & Magnezyum (400mg)", note: "Gece. Karaciğer glutatyon detoksu, Brain Fog temizliği ve sinir sistemini yatıştıran derin REM uykusu." },
        { name: "Balık Yağı / Alg Omega-3 & B12 (1000mcg)", note: "Etçil fazda 2000mg. Halvet (Vegan) fazına geçilince 1000mg Alg Omega-3 ve saf Metilkobalamin B12." }
    ],
    devices: [
        { name: "ActivaDose tDCS Cihazı", desc: "Beyne 1.5mA mikro elektrik akımı vererek nöroplastisiteyi ve odaklanmayı artıran askeri sınıf donanım." },
        { name: "BraiNet 10/20 Elektrot Şapkası", desc: "tDCS elektrotlarını beynin F3 (Öğrenme) ve Fp2 noktalarına milimetrik yerleştirmek için kullanılan medikal şapka." },
        { name: "Duyusal Yoksunluk Tankı (Flotation)", desc: "İçi epsom tuzu dolu karanlık kapsül. Yerçekimi, ışık ve ses sıfırlanır. Zihni formatlamak için kullanılır." },
        { name: "Muse 2 (Nöro-Geri Bildirim Başlığı)", desc: "Meditasyon ve zikir anında beyin dalgalarını (Alfa/Gama) ölçerek gerçek zamanlı kalp atışı kontrolü sağlayan cihaz." },
        { name: "Mavi Işık Blokaj Gözlüğü", desc: "Akşam 20:00'den sonra melatonin üretimini korumak ve sirkadiyen ritmi güvenceye almak için takılır." }
    ],
    activities: [
        { phase: "KATMAN 0-3: Zemin ve Usul", physical: "Postür Düzeltme, Core Kuvveti (Plank) & Loci Hafıza Pratiği", social: "Aktif Dinleme ve Sokratik Sorgulama. Fikrini savunma, soru sorarak karşındakinin mantığını çürüt.", wardrobe: "Minimalizm. Markasız temel renkler (Lacivert, Beyaz, Gri). Zihni yormayan sadelik.", fragrance: "Sandal Ağacı (Sandalwood) & Beyaz Misk. Odaklanmayı artıran temiz koku.", icon: "Target" },
        { phase: "KATMAN 4-6: Şiddet ve İrade", physical: "Ağır Boks, Sparring & Adrenalin Yönetimi", social: "Reddedilme Terapisi: Her gün bilerek reddedileceğin bir şey iste.", wardrobe: "Taktiksel Zırh. Tamamen siyah (All-Black). Askeri disiplini yansıtan dayanıklı kumaşlar.", fragrance: "Sedir Ağacı, Karabiber ve Deri. Topraklayıcı, agresif ve dominant.", icon: "Swords" },
        { phase: "KATMAN 7-8: Algı, Hitabet ve Müzakere", physical: "Hitabet/Diksiyon Kursu & Eskrim", social: "Frame Dominasyonu: Kalabalık masada kontrolü al. Topluluğa hitap et ve ses tonunla yönlendir.", wardrobe: "Terzi İşi (Bespoke) Otorite. Jilet gibi kesim koyu renk takım elbiseler.", fragrance: "Ud (Oud), Vetiver ve Bergamot. Sofistike 'Yatırımcı/Müzakereci' aurası.", icon: "Users" },
        { phase: "KATMAN 9-10: Güç ve Otorite", physical: "Powerlifting (Mutlak Güç İnşası) & GO Oyunu", social: "Makyavelist Gözlem: Kriz yarat veya görev delege et. Kimin sadık olduğunu sessizce kaydet.", wardrobe: "Sessiz Lüks (Old Money). Kaşmir kazaklar, özel dikim blazerlar.", fragrance: "Kehribar (Amber), Misk ve Tütün. Ağır, kalıcı, kurucu lider kokusu.", icon: "Hexagon" },
        { phase: "KATMAN 11-13: Siyaset ve Medeniyet", physical: "Binicilik (Liderlik) & Klasik Müzik İcrası", social: "Asabiyet Mühendisliği: Zıt görüşlü grupları ortak bir vizyon (veya düşman) etrafında birleştirme testi.", wardrobe: "Klasik ve Zamansız. Tweed ceketler, yün pantolonlar. Bin yıllık 'Devlet Adamı' postürü.", fragrance: "Gül (Taif Gülü), Paçuli ve Safran. Kadim sarayların mistik ağırlığı.", icon: "Globe" },
        { phase: "KATMAN 14 & 17: Sentez ve Ön-Halvet", physical: "Uzun Doğa Yürüyüşleri (Hiking) & Geleneksel Kaligrafi (Hat)", social: "Bağ Kesme: Seni aşağı çeken toksik bağları tamamen bitir.", wardrobe: "Organik ve Bol Kesim. Ham keten ve dökümlü kıyafetler. Gezgin aurası.", fragrance: "Yasemin, Mür (Myrrh) ve Akgünlük Tütsüsü.", icon: "Footprints" },
        { phase: "HALVET: 3. Göz ve Tasavvuf", physical: "Otofaji, Murakabe, Tummo Nefesi ve Qi Gong Esnemeleri", social: "MUTLAK SÜKUT YEMİNİ: İnsan yüzü görme. Dijital ekranları kapat. Aynada kendi nefsini parçala.", wardrobe: "Sıfır Gösteriş. Bembeyaz pamuklu cübbe/gömlek. Bedeni ve kibri tamamen örtme.", fragrance: "Saf Misk veya Has Ud Yağı. Melekleri ve uhreviyatı çeken sentetiksiz saf form.", icon: "Moon" }
    ]
};

export const PHASE_CONFIG = [
    { start: 1, end: 60, theme: "cyan", title: "Zemin, Metodoloji ve Usul", author: "Adler, Newport, Gazali, Şafii, Russell", colorClass: "from-cyan-900/40 to-blue-950/40 border-cyan-500/50 text-cyan-400", activity: "Postür Düzeltme, Core Kuvveti (Plank) & Loci Hafıza Pratiği", social: "Sokratik Sorgulama: Masada kendi fikrini savunma. Doğru sorularla safsatalarını kendi kendilerine çürütmelerini izle.", wardrobe: "Minimalizm ve Temizlik. Markasız temel renkler (Lacivert, Beyaz, Gri).", fragrance: "Sandal Ağacı (Sandalwood) & Beyaz Misk. Temiz ve nötr bir koku.", tactic: { method: "Analitik Haritalama & Kıyasi Okuma", action: "Öğrenmeyi öğren. Şüpheyi yık. Loci sarayını tasarla." } },
    { start: 61, end: 140, theme: "red", title: "Şiddet, Korku ve İnsan Doğası", author: "Grossman, Goggins, Taleb, Kafka (Alegori)", colorClass: "from-red-950/60 to-orange-950/40 border-red-600/50 text-red-500", activity: "Ağır Boks, Sparring & Adrenalin Yönetimi", social: "Reddedilme Terapisi ve İrkilme Testi: Sosyal baskı anında göz temasını koru.", wardrobe: "Taktiksel ve Atletik Zırh. Tamamen siyah (All-Black).", fragrance: "Sedir Ağacı (Cedarwood), Karabiber ve Deri. Yırtıcı savaşçı aurası.", tactic: { method: "Predator (Avcı) ve Diyalektik Okuma", action: "Bedensel korkuyu yen. Acı eşiğini kır." } },
    { start: 141, end: 220, theme: "orange", title: "Çerçeve Kontrolü, Hitabet ve Algı", author: "Klaff, Voss, Qaiman, Cicero, Gallo", colorClass: "from-orange-900/40 to-red-950/40 border-orange-500/50 text-orange-400", activity: "Hitabet/Diksiyon Kursu & Taktiksel Refleks (Eskrim)", social: "Frame Dominasyonu ve Retorik: Kalabalık masada kontrolü eline al.", wardrobe: "Terzi İşi (Bespoke) Otorite. Jilet gibi kesim koyu renk takım elbiseler.", fragrance: "Ud (Oud), Vetiver ve Bergamot. Yatırımcı/Müzakereci imza kokusu.", tactic: { method: "Pragmatik Saha Okuması", action: "Kitlelerin imgelerle nasıl yönetildiğini öğren." } },
    { start: 221, end: 310, theme: "purple", title: "Güç, Strateji ve Kurucu Otorite", author: "Machiavelli, Sun Tzu, Weber, Lee Kuan Yew", colorClass: "from-purple-900/40 to-fuchsia-950/40 border-purple-500/50 text-purple-400", activity: "Powerlifting (Mutlak Güç İnşası) & GO Oyunu", social: "Makyavelist Gözlem ve Delegasyon: Küçük krizler yarat veya bir projeyi başkalarına yönettir.", wardrobe: "Sessiz Lüks (Old Money) ve Kurucu Akıl. Kaşmir kazaklar, toprak tonları, özel dikim blazerlar.", fragrance: "Kehribar (Amber), Misk ve Tütün. Kurucu lider kokuları.", tactic: { method: "Makro-Senaryo ve Amoral Okuma", action: "Lee Kuan Yew'in devlet kurma zekasını öğren." } },
    { start: 311, end: 410, theme: "indigo", title: "İslam Siyaseti, Medeniyet ve Jeopolitik", author: "İbn Haldun, Canetti, Brzezinski, Orwell", colorClass: "from-indigo-900/40 to-blue-950/40 border-indigo-500/50 text-indigo-400", activity: "Binicilik (Liderlik Postürü) & Klasik Müzik İcrası", social: "Asabiyet Mühendisliği: Birbirini sevmeyen farklı iki grubu ortak bir vizyon etrafında birleştir.", wardrobe: "Klasik ve Zamansız (Timeless). Devlet Adamı / Bilge postürü.", fragrance: "Gül (Taif Gülü), Paçuli ve Safran. Kadim sarayların mistik ağırlığı.", tactic: { method: "Sinoptik Sentez & Ontolojik Çözümleme", action: "Amerikan jeopolitiği ile İslam aklını çarpıştır." } },
    { start: 411, end: 546, theme: "emerald", title: "Büyük Sentez ve Ön-Halvet Hazırlığı", author: "Izutsu, İkbal, Şems-i Tebrizi, Attar", colorClass: "from-emerald-900/40 to-teal-950/40 border-emerald-500/50 text-emerald-400", activity: "Uzun Doğa Yürüyüşleri (Hiking) & İnce Motor (Kaligrafi/Hat)", social: "Bağ Kesme İzolasyonu: Seni aşağı çeken ilişkileri tamamen bitir.", wardrobe: "Organik ve Bol Kesim. Ham keten, kenevir kumaşı. Dünyevi gösterişten uzaklaşan gezgin aurası.", fragrance: "Yasemin, Mür (Myrrh) ve Akgünlük Tütsüsü. İçe dönmeyi kolaylaştıran özler.", tactic: { method: "Semantik Analiz ve Hikmet Sentezi", action: "Batı rasyonalitesi ile evrensel hikmeti tek potada erit." } },
    { start: 547, end: 624, theme: "amber", title: "MUTLAK HALVET & 3. GÖZ", author: "Gazali, İbn Arabi, İmam Rabbani", colorClass: "from-amber-700/30 to-orange-950/60 border-amber-500/50 text-amber-400 shadow-[0_0_40px_rgba(245,158,11,0.2)]", activity: "Otofaji, Murakabe, Tummo Nefesi ve Qi Gong Esnemeleri", social: "MUTLAK SÜKUT YEMİNİ: İnsan yüzü görmek, dijital ekranlar YASAK.", wardrobe: "Sıfır Gösteriş. Bembeyaz pamuklu cübbe/gömlek. Kibrini tamamen örtme.", fragrance: "Saf Misk veya Has Ud Yağı. Sentetik kimyasal içermeyen en saf formlar.", tactic: { method: "Mükaşefe (Batıni) Okuması", action: "Analitik aklı tamamen KAPAT! Gözlerini yum, kalbine indir." } }
];

export const DETAILED_SCHEDULE = [
    { start: 1, end: 5, book: "Nasıl Okumalı", author: "Mortimer Adler", theme: "cyan", phase: "Zemin", tactic: "Analitik Haritalama", action: "4 okuma seviyesini ezberle. Loci metodunu kur." },
    { start: 6, end: 12, book: "Deep Work & Make It Stick", author: "Newport & Brown", theme: "cyan", phase: "Öğrenme", tactic: "İnspeksiyonel Tarama", action: "Odaklanma matematiğini çıkar." },
    { start: 13, end: 25, book: "Batı Felsefesi Tarihi", author: "Bertrand Russell", theme: "cyan", phase: "Felsefe", tactic: "Diyalektik Okuma", action: "Antik Yunan'dan bugüne Batı'nın zihin haritasını çıkar." },
    { start: 26, end: 32, book: "İslam Düşüncesine Giriş", author: "M. M. Şerif", theme: "cyan", phase: "İslam Felsefesi", tactic: "Karşılaştırmalı Okuma", action: "Russell'ın tezlerini bu kitapla çürüt." },
    { start: 33, end: 50, book: "Kur'an Meali & Siyer", author: "Vahiy & Tarih", theme: "cyan", phase: "İman", tactic: "Kalbi ve Sistematik", action: "Ayetleri stratejik bir yaşam kılavuzu olarak kazı." },
    { start: 51, end: 57, book: "El-Munkız mine'd-Dalâl", author: "İmam Gazali", theme: "cyan", phase: "Kelam", tactic: "Şüphe ve Yıkım", action: "Gazali'nin şüphe krizini nasıl aştığını satır satır çalış." },
    { start: 58, end: 65, book: "Organon & Er-Risâle", author: "Aristoteles & Şafii", theme: "cyan", phase: "Usul", tactic: "Mantıksal Çözümleme", action: "Tümdengelim şablonlarını ezberle." },
    { start: 66, end: 74, book: "Bilimsel Devrimlerin Yapısı", author: "Thomas Kuhn", theme: "red", phase: "Epistemoloji", tactic: "Paradigma Okuması", action: "Eski inançların nasıl yıkılıp yeni sistemlerin kurulduğunu anla." },
    { start: 75, end: 84, book: "Kara Kuğu & Antikırılganlık", author: "Nassim Taleb", theme: "red", phase: "Risk", tactic: "Kaos Analizi", action: "Kaostan güçlenerek çıkmanın yollarını formülize et." },
    { start: 85, end: 90, book: "İnsanın Anlam Arayışı", author: "Viktor Frankl", theme: "red", phase: "İrade", tactic: "Varoluşsal Yüzleşme", action: "Toplama kampı psikolojisini idrak et." },
    { start: 91, end: 97, book: "Can't Hurt Me", author: "David Goggins", theme: "red", phase: "Dayanıklılık", tactic: "Biyolojik Meydan Okuma", action: "Zihnin 'pes et' dediği noktada %40 kuralını hatırla." },
    { start: 98, end: 106, book: "On Combat & The Flinch", author: "Grossman & Smith", theme: "red", phase: "Korku", tactic: "Taktiksel Korku Yönetimi", action: "Ölümcül stres anında nefes ve kalp atışını kontrol etmeyi öğren." },
    { start: 107, end: 115, book: "Kitlelerin Psikolojisi", author: "Gustave Le Bon", theme: "orange", phase: "Kitle", tactic: "Sosyo-Psikolojik Analiz", action: "Bireyin kitle içinde nasıl zekasını kaybettiğini formülleştir." },
    { start: 116, end: 125, book: "Propaganda", author: "Edward Bernays", theme: "orange", phase: "Algı", tactic: "Avcı (Predator) Okuması", action: "Görünmez iktidarın zihinleri nasıl şekillendirdiğini yakala." },
    { start: 126, end: 132, book: "Pitch Anything & TED Gibi Konuş", author: "Klaff & Gallo", theme: "orange", phase: "Müzakere & Sahne", tactic: "Çerçeve Dominasyonu", action: "Masadaki alfa konumunu koru." },
    { start: 133, end: 138, book: "Hatip Üzerine & S. Dialogue", author: "Cicero & Qaiman", theme: "orange", phase: "Retorik", tactic: "Kadim İkna ve Retorik", action: "Roma'lı bir hatip gibi ayarla. Sözcükleri silah gibi kullan." },
    { start: 139, end: 145, book: "Asla Farkı Bölüşme", author: "Chris Voss", theme: "orange", phase: "Kriz", tactic: "Taktiksel Empati", action: "FBI aynalama tekniklerini ezberle. Karşı tarafı kan dökmeden ikna et." },
    { start: 146, end: 155, book: "Savaş Sanatı & Clausewitz", author: "Sun Tzu & Clausewitz", theme: "purple", phase: "Strateji", tactic: "Realpolitik Analiz", action: "Düşmanı savaşmadan yenme ve kuşatma sanatını iş hayatına uyarla." },
    { start: 156, end: 165, book: "Prens & 48 Yasa", author: "Machiavelli & Greene", theme: "purple", phase: "Güç", tactic: "Amoral (Duygusuz) Analiz", action: "Sana kurulacak kumpasları önceden görmek için oku." },
    { start: 166, end: 175, book: "Ekonomi ve Toplum (Otorite)", author: "Max Weber", theme: "purple", phase: "Otorite", tactic: "Sosyolojik Okuma", action: "Karizmatik ve Yasal otoriteyi nasıl inşa edeceğini planla." },
    { start: 176, end: 185, book: "The Sovereign Individual", author: "Davidson", theme: "purple", phase: "Fütürizm", tactic: "Sistem Analizi", action: "Ulus-devletlerin çöküşü ve bireysel otonominin inşasını tasarla." },
    { start: 186, end: 195, book: "From Third World to First", author: "Lee Kuan Yew", theme: "purple", phase: "Kurucu Akıl", tactic: "Pratik Devlet Aklı", action: "Singapur'un bataklıktan zirveye çıkışındaki 'kurucu liderlik' sırlarını yaz." },
    { start: 196, end: 215, book: "Kitleler ve İktidar", author: "Elias Canetti", theme: "indigo", phase: "Siyaset", tactic: "Ontolojik Çözümleme", action: "İktidarın, kitleleri ölüm korkusuyla nasıl var ettiğini idrak et." },
    { start: 216, end: 235, book: "Mukaddime", author: "İbn Haldun", theme: "indigo", phase: "Makro Tarih", tactic: "Asabiyet Sentezi", action: "Bedevilikten medeniyete geçiş ve devletlerin çöküş döngülerini haritala." },
    { start: 236, end: 245, book: "Siyasetname", author: "Nizamülmülk", theme: "indigo", phase: "İslam Devleti", tactic: "Teşkilat Okuması", action: "Kadim istihbarat ve liyakat sistemini günümüz teşkilatlarına uyarla." },
    { start: 246, end: 255, book: "Büyük Satranç Tahtası", author: "Z. Brzezinski", theme: "indigo", phase: "Jeopolitik", tactic: "Fay Hattı Analizi", action: "Amerikan imparatorluğunun dünyayı nasıl yönettiğini harita üzerinde gör." },
    { start: 256, end: 275, book: "Tüfek, Mikrop ve Çelik & Huntington", author: "Diamond & Huntington", theme: "indigo", phase: "Medeniyet", tactic: "Coğrafi Kader Sentezi", action: "Kültürlerin neden çatıştığını ve maddi üstünlüğün sırrını çöz." },
    { start: 276, end: 295, book: "Kutsal Metinler (Tanah, İncil, Tao)", author: "Kadim Metinler", theme: "indigo", phase: "Dinler Tarihi", tactic: "Teolojik DNA Okuması", action: "Eleştirmeden oku. Batı'nın ve Asya'nın inanç kodlarına sız." },
    { start: 296, end: 305, book: "1984 & Hayvan Çiftliği", author: "George Orwell", theme: "emerald", phase: "Edebiyat / Alegori", tactic: "Sistem Eleştirisi", action: "Dilin bozulması ve gücün yozlaşmasını kurgu üzerinden izle." },
    { start: 306, end: 315, book: "Veba & Dönüşüm", author: "Camus & Kafka", theme: "emerald", phase: "Edebiyat / Varoluş", tactic: "Bürokratik Kâbus", action: "Sistemin bireyi nasıl böceğe çevirdiğini anla." },
    { start: 316, end: 335, book: "Kur'an'da Allah ve İnsan", author: "T. Izutsu", theme: "emerald", phase: "Sentez", tactic: "Semantik Kazı", action: "Kavramların köklerine inerek İslam aklını zirvede anla." },
    { start: 336, end: 350, book: "Nehcü'l-Belağa", author: "Hz. Ali", theme: "emerald", phase: "Sentez", tactic: "Belagat ve Hikmet", action: "Valilik emirnamelerini modern bir devlet anayasası gibi çalış." },
    { start: 351, end: 365, book: "Mantıku't-Tayr (Kuşların Dili)", author: "F. Attar", theme: "emerald", phase: "Ön-Halvet", tactic: "Alegorik İçe Dönüş", action: "Nefsini 7 vadiden geçir. İzolasyona başla." },
    { start: 366, end: 380, book: "Makâlât", author: "Şems-i Tebrizi", theme: "emerald", phase: "Ön-Halvet", tactic: "Sert Yüzleşme", action: "Şems'in sözleriyle içindeki tüm kibri yargıla." },
    { start: 381, end: 546, book: "Külliyat Sinoptik Taraması", author: "Kalan 190 Eser", theme: "emerald", phase: "Genel Sentez", tactic: "Hızlı Tarama ve Kodlama", action: "Günde 1 kitap. Ana fikirlerini tarayıp Loci hafıza sarayındaki boşlukları doldur." },
    { start: 547, end: 575, book: "İhyâ'u Ulûmi'd-Dîn", author: "İmam Gazali", theme: "amber", phase: "Halvet Faz 1", tactic: "Batıni Muhasebe", action: "SÜKUT YEMİNİ. Analitik aklı kapat. Her sayfada gözyaşıyla tövbe et." },
    { start: 576, end: 600, book: "Füsûsu'l-Hikem & Fütûhat", author: "İbn Arabi", theme: "amber", phase: "Halvet Faz 2", tactic: "Tefekkür ve Seyr", action: "3. GÖZ AÇILIŞI. Mantık arama." },
    { start: 601, end: 624, book: "Mektubat", author: "İmam Rabbani", theme: "amber", phase: "Kemalat", tactic: "Sünnet Sentezi", action: "Cezbeden (sarhoşluktan) ayıl. Halka dönmeye hazırlan." }
];
